name:                hyahtzee2
version:             0.1.0.0
github:              "DamienCassou/hyahtzee2"
license:             BSD3
author:              "Damien Cassou"
maintainer:          "damien@cassou.me"
copyright:           "2021 Damien Cassou"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/DamienCassou/hyahtzee2#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hyahtzee2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hyahtzee2

tests:
  hyahtzee2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hyahtzee2
    - tasty
    - tasty-hspec
