on: [push]
name: test
jobs:
  runhaskell:
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - uses: cachix/cachix-action@v8
        with:
          name: nix-haskell-test
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
      - run: nix-shell --run 'hlint --version'
      - run: nix-shell --run 'hlint .'
      - run: nix-shell --run 'stack test'
      - run: nix-shell --run "echo OK"
